services:
  - type: worker
    name: educonnect-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot_educonnect.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9   # ðŸ‘ˆ MUY IMPORTANTE â€” versiÃ³n estable compatible
